In [76]:
!pip install pandas numpy plotly openpyxl sqlalchemy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.0)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
from sqlalchemy import create_engine

In [47]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [48]:
import os

os.listdir('/content/drive/MyDrive/')

['Colab Notebooks',
 'Basic concept 90 questions 2020.pdf',
 'Untitled form (3).gform',
 'Untitled form (2).gform',
 '3e6e0701-1498-421b-865a-b609a7bdf3ef',
 '2dbb02a2-bbec-4764-8a37-f9a1417b4ce4',
 'Screenshot_20210222-165951.png',
 'zsg-syyc-eqc - Jul 9, 2021 (1).pdf',
 'zsg-syyc-eqc - Jul 9, 2021.pdf',
 'Untitled form (1).gform',
 'Untitled form.gform',
 'Image to PDF 20210914 16.52.38.pdf',
 'ADITHYA VINOD S1A ROLL NO 2.jpg',
 'aadhu',
 'HSSRptr_+2 Botany VIJAYABHERI FINAL.pdf',
 'Vijayabheri Plus 2 Zoology 2021-22 (based on exam capsule).pdf',
 '20220228_210008.png',
 'Modern-Neon-Party-Club-Flyer-Tem (6).mp4',
 'VID-20220527-WA0072.mp4',
 'IMG-20220702-WA0004.jpg',
 'IMG-20221220-WA0051.jpg',
 'IMG-20230331-WA0009.jpg',
 'Adithya vinod fee details.pdf',
 'DOC-20230613-WA0006..pdf',
 'DBMS EXP 1.xlsx',
 'IMG-5932.jpg',
 'nkw-uxfp-uem - Aug 6, 2023.pdf',
 'DSA_module_1_Final.pdf',
 'Untitled presentation.gslides',
 'Classroom',
 'CALCULATOR  PROJECT (1).pdf',
 'CALCULATOR  PROJECT.pdf',
 'Validation form project (1).pdf',
 'Validation form project.pdf',
 'start_here.gdoc',
 'no-data.gdoc',
 'Document from Adithya Vinod',
 'Google AI Studio',
 'index (4).gdoc',
 'index (5).gdoc',
 'preprints202503.1969.v1_copy.pdf',
 'lab task-DVW (1).gdoc',
 'lab task-DVW.gdoc',
 'dont add executive.gdoc',
 'add some of he results if possible.gdoc',
 'make the name as customer shopping behavior.gdoc',
 'D 78773 copy.jpg',
 '2203031250004_AdithyaVinod.pdf',
 'Uber_Request_cleaned_Data.csv',
 'Uber_A.csv',
 'Medibuddy Insurance Data Price.xlsx',
 'Medibuddy insurance data personal details.xlsx',
 'Medibuddy Insurance Data Price.csv',
 'Medibuddy insurance data personal details.csv',
 'InteractiveSheet_2026-01-15_17_17_24.gsheet',
 'InteractiveSheet_2026-01-15_17_41_12.gsheet',
 'InteractiveSheet_2026-01-15_19_46_26.gsheet',
 'InteractiveSheet_2026-01-17_17_11_03.gsheet',
 'InteractiveSheet_2026-01-17_18_13_29.gsheet',
 'InteractiveSheet_2026-01-17_18_27_21.gsheet',
 'InteractiveSheet_2026-01-18_05_19_03.gsheet',
 'InteractiveSheet_2026-01-18_05_20_57.gsheet',
 'InteractiveSheet_2026-01-18_05_21_20.gsheet',
 'InteractiveSheet_2026-01-20_13_13_48.gsheet',
 'InteractiveSheet_2026-01-21_04_30_40.gsheet',
 'InteractiveSheet_2026-01-21_04_32_47.gsheet',
 'InteractiveSheet_2026-01-24_16_30_56.gsheet',
 'MediBuddy',
 'Explanatory video - MediBuddy',
 'Uber Supply Demand Gap',
 ' Explainatory video',
 'AdithyaVinod_resume.pdf',
 'games (1).csv',
 'vgsales (1).csv',
 'Video Game Sales and Engagement Analysis',
 'Video explanation',
 'iTunes_videoExplanation',
 'Apple iTunes Music Data Analysis - Project',
 'Bellabeat Smart Device Data Analysis (Strava)',
 'Bellabeat(Strava) Video explanation',
 'InteractiveSheet_2026-03-13_16_46_47.gsheet',
 '03c118d4-035a-42bd-85fe-ecef6533f293_copy.pdf',
 'Bird_Monitoring_Data_FOREST.XLSX',
 'Bird_Monitoring_Data_GRASSLAND.XLSX',
 '25TLPCW1SC23380.pdf',
 'Copy of Bird_Monitoring_Data_FOREST.XLSX',
 'Bird']

In [49]:
os.listdir('/content/drive/MyDrive/Bird/')

['Bird_Monitoring_Data_FOREST.XLSX', 'Bird_Monitoring_Data_GRASSLAND.XLSX']

In [51]:
import pandas as pd

# File names (must match uploaded names exactly)
forest_file = "Bird_Monitoring_Data_FOREST.XLSX"
grass_file = "Bird_Monitoring_Data_GRASSLAND.XLSX"

# Read Excel files
forest_xls = pd.ExcelFile(forest_file)
grass_xls = pd.ExcelFile(grass_file)

df_list = []

# 🔹 FOREST data
for sheet in forest_xls.sheet_names:
    temp = pd.read_excel(forest_xls, sheet_name=sheet)
    temp["Location_Type"] = "Forest"  # Add habitat
    temp["Admin_Unit_Code"] = sheet   # Track sheet
    df_list.append(temp)

# 🔹 GRASSLAND data
for sheet in grass_xls.sheet_names:
    temp = pd.read_excel(grass_xls, sheet_name=sheet)
    temp["Location_Type"] = "Grassland"
    temp["Admin_Unit_Code"] = sheet
    df_list.append(temp)

# 🔹 Combine all sheets
df = pd.concat(df_list, ignore_index=True)

# Preview
df.head()

/tmp/ipykernel_5889/3566438260.py:28: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

,Admin_Unit_Code,Sub_Unit_Code,Site_Name,Plot_Name,Location_Type,Year,Date,Start_Time,End_Time,Observer,...,PIF_Watchlist_Status,Regional_Stewardship_Status,Temperature,Humidity,Sky,Wind,Disturbance,Initial_Three_Min_Cnt,TaxonCode,Previously_Obs
0,ANTI,NaN,ANTI 1,ANTI-0036,Forest,2018,2018-05-22,06:19:00,06:29:00,Elizabeth Oswald,...,False,True,19.9,79.400002,Cloudy/Overcast,Calm (< 1 mph) smoke rises vertically,No effect on count,True,NaN,NaN
1,ANTI,NaN,ANTI 1,ANTI-0036,Forest,2018,2018-05-22,06:19:00,06:29:00,Elizabeth Oswald,...,False,False,19.9,79.400002,Cloudy/Overcast,Calm (< 1 mph) smoke rises vertically,No effect on count,True,NaN,NaN
2,ANTI,NaN,ANTI 1,ANTI-0036,Forest,2018,2018-05-22,06:19:00,06:29:00,Elizabeth Oswald,...,False,False,19.9,79.400002,Cloudy/Overcast,Calm (< 1 mph) smoke rises vertically,No effect on count,False,NaN,NaN
3,ANTI,NaN,ANTI 1,ANTI-0036,Forest,2018,2018-05-22,06:19:00,06:29:00,Elizabeth Oswald,...,False,False,19.9,79.400002,Cloudy/Overcast,Calm (< 1 mph) smoke rises vertically,No effect on count,False,NaN,NaN
4,ANTI,NaN,ANTI 1,ANTI-0036,Forest,2018,2018-05-22,06:19:00,06:29:00,Elizabeth Oswald,...,False,False,19.9,79.400002,Cloudy/Overcast,Calm (< 1 mph) smoke rises vertically,No effect on count,False,NaN,NaN

In [52]:
df.shape
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17077 entries, 0 to 17076
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Admin_Unit_Code              17077 non-null  object
 1   Sub_Unit_Code                722 non-null    object
 2   Site_Name                    8546 non-null   object
 3   Plot_Name                    17077 non-null  object
 4   Location_Type                17077 non-null  object
 5   Year                         17077 non-null  object
 6   Date                         17077 non-null  datetime64[ns]
 7   Start_Time                   17077 non-null  object
 8   End_Time                     17077 non-null  object
 9   Observer                     17077 non-null  object
 10  Visit                        17077 non-null  object
 11  Interval_Length              17077 non-null  object
 12  ID_Method                    17075 non-null  object
 13  Distance                     15591 non-null  object
 14  Flyover_Observed             17077 non-null  object
 15  Sex                          11894 non-null  object
 16  Common_Name                  17077 non-null  object
 17  Scientific_Name              17077 non-null  object
 18  AcceptedTSN                  17044 non-null  float64
 19  NPSTaxonCode                 8546 non-null   float64
 20  AOU_Code                     17077 non-null  object
 21  PIF_Watchlist_Status         17077 non-null  object
 22  Regional_Stewardship_Status  17077 non-null  object
 23  Temperature                  17077 non-null  float64
 24  Humidity                     17077 non-null  float64
 25  Sky                          17077 non-null  object
 26  Wind                         17077 non-null  object
 27  Disturbance                  17077 non-null  object
 28  Initial_Three_Min_Cnt        17077 non-null  object
 29  TaxonCode                    8529 non-null   float64
 30  Previously_Obs               8531 non-null   object
dtypes: datetime64[ns](1), float64(5), object(25)
memory usage: 4.0+ MB

Admin_Unit_Code                    0
Sub_Unit_Code                  16355
Site_Name                       8531
Plot_Name                          0
Location_Type                      0
Year                               0
Date                               0
Start_Time                         0
End_Time                           0
Observer                           0
Visit                              0
Interval_Length                    0
ID_Method                          2
Distance                        1486
Flyover_Observed                   0
Sex                             5183
Common_Name                        0
Scientific_Name                    0
AcceptedTSN                       33
NPSTaxonCode                    8531
AOU_Code                           0
PIF_Watchlist_Status               0
Regional_Stewardship_Status        0
Temperature                        0
Humidity                           0
Sky                                0
Wind                               0
Disturbance                        0
Initial_Three_Min_Cnt              0
TaxonCode                       8548
Previously_Obs                  8546
dtype: int64

# **DATA CLEANING**

In [53]:
df["Temperature"] = df["Temperature"].fillna(df["Temperature"].mean())
df["Humidity"] = df["Humidity"].fillna(df["Humidity"].median())

In [54]:
df.dropna(subset=["Scientific_Name"], inplace=True)

In [55]:
df.drop_duplicates(inplace=True)

In [56]:
cols_to_drop = ["AcceptedTSN", "NPSTaxonCode", "AOU_Code"]
df.drop(columns=cols_to_drop, inplace=True, errors='ignore')

In [57]:
df["Date"] = pd.to_datetime(df["Date"], errors='coerce')

df["Start_Time"] = pd.to_datetime(df["Start_Time"], errors='coerce')
df["End_Time"] = pd.to_datetime(df["End_Time"], errors='coerce')

In [58]:
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Hour"] = df["Start_Time"].dt.hour

# Season column
def get_season(m):
    if m in [12,1,2]: return "Winter"
    elif m in [3,4,5]: return "Summer"
    elif m in [6,7,8]: return "Monsoon"
    else: return "Autumn"

df["Season"] = df["Month"].apply(get_season)

# Observation duration
df["Observation_Duration"] = (df["End_Time"] - df["Start_Time"]).dt.seconds / 60

In [ ]:
df.to_csv("/content/cleaned_bird_data.csv", index=False)

# **EDA**

## Total Species

In [59]:
print("Total Species:", df["Scientific_Name"].nunique())

Total Species: 127

## Top 10 Species

In [60]:
top_species = df["Common_Name"].value_counts().head(10)
top_species

Common_Name
Northern Cardinal          1125
Carolina Wren               993
Red-eyed Vireo              738
Eastern Tufted Titmouse     720
Indigo Bunting              611
Eastern Wood-Pewee          574
Field Sparrow               492
Red-bellied Woodpecker      489
American Robin              470
Acadian Flycatcher          462
Name: count, dtype: int64

## Habitat Diversity

In [61]:
df.groupby("Location_Type")["Scientific_Name"].nunique()

Location_Type
Forest       108
Grassland    107
Name: Scientific_Name, dtype: int64

## Seasonal Trends

In [62]:
df.groupby("Season").size()

Season
Monsoon    10508
Summer      4864
dtype: int64

## Hourly Activity

In [63]:
df.groupby("Hour").size()

Series([], dtype: int64)

## Environmental Impact

In [64]:
df.groupby("Sky").size()
df.groupby("Wind").size()

Wind
Calm (< 1 mph) smoke rises vertically         4210
Gentle breeze (8-12 mph), leaves in motion     365
Light air movement (1-3 mph) smoke drifts     7636
Light breeze (4-7 mph) wind felt on face      3161
dtype: int64

## Conservation Analysis

In [65]:
df["PIF_Watchlist_Status"].value_counts()

PIF_Watchlist_Status
False    14994
True       378
Name: count, dtype: int64

# **VISUALIZATION (Plotly)**

In [73]:
import plotly.io as pio
pio.templates.default = "plotly_white"

## 📊 Top Species

In [77]:
fig = px.bar(top_species, title="Top 10 Bird Species")
fig.show()

## 📊 Habitat Distribution

In [78]:
fig = px.pie(df, names="Location_Type", title="Habitat Distribution")
fig.show()

## 📊 Seasonal Trends

In [79]:
season_df = df.groupby("Season").size().reset_index(name="Count")

fig = px.bar(season_df, x="Season", y="Count", color="Season")
fig.show()

## 📊 Hourly Activity

In [80]:
hour_df = df.groupby("Hour").size().reset_index(name="Count")

fig = px.line(hour_df, x="Hour", y="Count", title="Bird Activity by Hour")
fig.show()

## 📊 Environment Impact

In [81]:
fig = px.scatter(df, x="Temperature", y="Humidity", color="Location_Type")
fig.show()

# **SQL DATABASE**

In [82]:
engine = create_engine("sqlite:///birds.db")

df.to_sql("bird_data", engine, if_exists="replace", index=False)

15372

## **SQL Queries**

## Top Species

In [83]:
pd.read_sql("""
SELECT Common_Name, COUNT(*) as count
FROM bird_data
GROUP BY Common_Name
ORDER BY count DESC
LIMIT 10;
""", engine)

               Common_Name  count
0        Northern Cardinal   1125
1            Carolina Wren    993
2           Red-eyed Vireo    738
3  Eastern Tufted Titmouse    720
4           Indigo Bunting    611
5       Eastern Wood-Pewee    574
6            Field Sparrow    492
7   Red-bellied Woodpecker    489
8           American Robin    470
9       Acadian Flycatcher    462

## Habitat Diversity

In [84]:
pd.read_sql("""
SELECT Location_Type, COUNT(DISTINCT Scientific_Name) as species_count
FROM bird_data
GROUP BY Location_Type;
""", engine)

  Location_Type  species_count
0        Forest            108
1     Grassland            107

## Seasonal Trends

In [85]:
pd.read_sql("""
SELECT Season, COUNT(*) as observations
FROM bird_data
GROUP BY Season;
""", engine)

    Season  observations
0  Monsoon         10508
1   Summer          4864

## At-Risk Species

In [86]:
pd.read_sql("""
SELECT Common_Name, COUNT(*)
FROM bird_data
WHERE PIF_Watchlist_Status = 'TRUE'
GROUP BY Common_Name;
""", engine)

Empty DataFrame
Columns: [Common_Name, COUNT(*)]
Index: []

In [87]:
from google.colab import files
files.download("cleaned_bird_data.csv")

# **FINAL INSIGHTS**

## - Forest habitats show higher species diversity compared to grasslands.
## - Bird activity peaks during early morning hours.
## - Seasonal trends indicate higher observations during summer and monsoon.
## - Weather conditions like clear skies improve bird visibility.  
## - Several species fall under conservation watchlist indicating ecological concern.